export interface Flight {
  recordStatus: any; //
  lastDateModified: any; //
  lastTimeModified: any; //
  lastUserToModify: any; //
  legDepartureDate: any; //
  airlineCode: any; //
  identifier: any; //
  sequence: any; //
  flightOriginDay: any; // skip
  numericFlightDate: any; //
  numGMTDate: any; //
  STDudt: any; //
  STAudt: any; //
  tailNumber: any; //
  numLastDateModified: any; // skip
  flightStatus: any; //
  origin: any; //
  STDLocal: any; //
  dispatchDesk: any; //
  STDGMTVariance: any; //
  destination: any; //
  STALocal: any; //
  STAGMTVariance: any; //
  OAGEquipmentType: any; //
  ACConfiguration: any; //
  serviceType: any; //
  originGate: any; //
  ETDlocal: any; //
  ETDudt: any; //
  TAXIutc: any; //
  OUTudt: any; //
  OFFudt: any; //
  destinationGate: any; //
  ETAlocal: any; //
  ETAudt: any; //
  ONudt: any; //
  INudt: any; //
  previousTailNumber: any; //
  ETE: any; //
  DCNutc: any; //
  ETOutc: any; //
  EONutc: any; //
  EDTCutc: any; //
  flightType: any; //
  newDepartureCity: any; //
  newArrivalCity: any; //
  SchedOAGEquipType: any; //
  OAGEquipSubType: any; //
  csvFSDailyID: any; //
  tailNumBeforeCancel: any; //
  CTAUTC: any; //
  cancelled: any; //
  replaced: any; //
  ATCStatus: any; //
  scheduledFlightType: any; //
  aircraftRouting: any; //
  mealService: any; //
  hub: any; //
  landingRestriction: any; //
  headStartFlight: any; //
  actualDeparture: any; //
  specialFlight: any; //
  actualArrival: any; //
  scheduledTaxiOut: any; //
  scheduledTaxiIn: any; //
  STOSetByUser: any; //
  STISetByUser: any; //
  CTFlightNumber: any; //
}
