// model definition for individual flights
// Flight3 means we are pulling data from the collection "Flight3s" which contains MVT Stage 3 flights

const mongoose = require("mongoose");
const Schema = mongoose.Schema;

var Flight3 = mongoose.model("Flight3", new Schema ({
  recordStatus: String,
  lastDateModified: String,
  lastTimeModified: String,
  lastUserToModify: String,
  legDepartureDate: String,
  airlineCode: String,
  identifier: String,
  sequence: String,
  flightOriginDay: String,
  numericFlightDate: String,
  numGMTDate: String,
  STDudt: String,
  STAudt: String,
  tailNumber: String,
  numLastDateModified: String,
  flightStatus: String,
  origin: String,
  STDLocal: String,
  dispatchDesk: String,
  STDGMTVariance: String,
  destination: String,
  STALocal: String,
  STAGMTVariance: String,
  OAGEquipmentType: String,
  ACConfiguration: String,
  serviceType: String,
  originGate: String,
  ETDlocal: String,
  ETDudt: String,
  TAXIutc: String,
  OUTudt: String,
  OFFudt: String,
  destinationGate: String,
  ETAlocal: String,
  ETAudt: String,
  ONudt: String,
  INudt: String,
  previousTailNumber: String,
  ETE: String,
  DCNutc: String,
  ETOutc: String,
  EONutc: String,
  EDTCutc: String,
  flightType: String,
  newDepartureCity: String,
  newArrivalCity: String,
  SchedOAGEquipType: String,
  OAGEquipSubType: String,
  csvFSDailyID: String,
  tailNumBeforeCancel: String,
  CTAUTC: String,
  cancelled: String,
  replaced: String,
  ATCStatus: String,
  scheduledFlightType: String,
  aircraftRouting: String,
  mealService: String,
  hub: String,
  landingRestriction: String,
  headStartFlight: String,
  actualDeparture: String,
  specialFlight: String,
  actualArrival: String,
  scheduledTaxiOut: String,
  scheduledTaxiIn: String,
  STOSetByUser: String,
  STISetByUser: String,
  CTFlightNumber: String
}), 'Flight3s');

module.exports = { Flight3 };
